
package com.mwendapeter.gmail.webserver;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AddNumService", targetNamespace = "http://webserver.gmail.mwendapeter.com/", wsdlLocation = "http://localhost:8080/APP/AddNum?wsdl")
public class AddNumService
    extends Service
{

    private final static URL ADDNUMSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADDNUMSERVICE_EXCEPTION;
    private final static QName ADDNUMSERVICE_QNAME = new QName("http://webserver.gmail.mwendapeter.com/", "AddNumService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/APP/AddNum?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADDNUMSERVICE_WSDL_LOCATION = url;
        ADDNUMSERVICE_EXCEPTION = e;
    }

    public AddNumService() {
        super(__getWsdlLocation(), ADDNUMSERVICE_QNAME);
    }

    public AddNumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADDNUMSERVICE_QNAME, features);
    }

    public AddNumService(URL wsdlLocation) {
        super(wsdlLocation, ADDNUMSERVICE_QNAME);
    }

    public AddNumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADDNUMSERVICE_QNAME, features);
    }

    public AddNumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddNumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AppAddNum
     */
    @WebEndpoint(name = "AddNumPort")
    public AppAddNum getAddNumPort() {
        return super.getPort(new QName("http://webserver.gmail.mwendapeter.com/", "AddNumPort"), AppAddNum.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppAddNum
     */
    @WebEndpoint(name = "AddNumPort")
    public AppAddNum getAddNumPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserver.gmail.mwendapeter.com/", "AddNumPort"), AppAddNum.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADDNUMSERVICE_EXCEPTION!= null) {
            throw ADDNUMSERVICE_EXCEPTION;
        }
        return ADDNUMSERVICE_WSDL_LOCATION;
    }

}
